<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class TPais extends Model
{
    use HasFactory;
    protected $table = "tpais";

    public function getRouteKeyName()
    {
//        return parent::getRouteKeyName(); // TODO: Change the autogenerated stub
        return "url";
    }

   /* public function destinos()
    {
        return $this->belongsTo(TPais::class, 'idpais');
    }*/

    public function destino()
    {
        return $this->hasMany(TDestino::class, 'idpais','id');
    }

    public function propiedades()
    {
        return $this->hasMany(TPaisPropiedades::class, 'idpais');
    }

    public function teams()
    {
        return $this->belongsToMany(TTeam::class, 'tteams_pais', 'idpais', 'idteam');
    }

    public function posts()
    {
        return $this->belongsToMany(TBlog_post::class, 'posts_pais', 'pais_id', 'post_id');
    }

    // App/Models/TPais.php
    public function categorias()
    {
        return $this->belongsToMany(
            TCategoria::class,
            'tpais_categoria',
            'pais_id',
            'categoria_id'
        )->withTimestamps();
    }

}
